routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Admin routes that can be accessed only from the non-www main domain.
|
*/

Route::group(['domain' => env('APP_DOMAIN')], function() {

    // Facebook Messenger Webhooks
    Route::get('/messenger', 'Messenger\MessengerController@incoming');
    Route::post('/messenger', 'Messenger\MessengerController@incoming');
    Route::get('/messenger-test', 'Messenger\MessengerTestController@incoming');
    Route::post('/messenger-test', 'Messenger\MessengerTestController@incoming');

    // Facebook Webhooks
    Route::get('/facebook', 'Admin\FacebookController@incoming');
    Route::post('/facebook', 'Admin\FacebookController@incoming');

    // Instagram Webhooks
    Route::get('/instagram', 'Admin\InstagramController@incoming');
    Route::post('/instagram', 'Admin\InstagramController@incoming');

    // Shopify Webhooks
    Route::get('/shopify', 'Admin\ShopifyController@incoming');
    Route::post('/shopify', 'Admin\ShopifyController@incoming');

    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register-invite', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::get('register-boutiquehub', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

    Route::get('/', 'Admin\WelcomeController@index');
    Route::get('contact', 'Admin\WelcomeController@contact');
    Route::get('pricing', 'Admin\WelcomeController@pricing');

    Route::get('facebook-login/callback', 'Shop\SocialAuthController@redirectToShop');
    Route::get('instagram-connect/callback', 'Admin\InstagramController@callback');

    Route::group(['middleware' => ['auth', 'shop.not-created']], function() {
        Route::get('admin/setup/step-1', 'Admin\CreateShopController@index');
        Route::post('admin/setup/step-1', 'Admin\CreateShopController@newShop');
        Route::post('admin/setup/hear-about-us', 'Admin\CreateShopController@setHearAboutUs');
        Route::post('admin/setup/billing-plan', 'Admin\CreateShopController@setBillingPlan');
    });

    Route::group(['middleware' => ['auth', 'shop.created', 'shop.has-no-card']], function() {
        Route::get('admin/setup/step-2', 'Admin\CreateShopController@card');
        Route::post('admin/setup/step-2', 'Admin\CreateShopController@setCard');
    });

    Route::group(['middleware' => ['auth', 'shop.created', 'shop.has-card']], function() {

        Route::get('admin', 'Admin\DashboardController@index');

        Route::group(['middleware' => ['can:superadmin']], function() {
            Route::get('admin/setup', 'Admin\SettingsController@shop');
            Route::get('admin/setup/shipping', 'Admin\SettingsController@shipping');
            Route::get('admin/setup/shipping/prepay-labels', 'Admin\SettingsController@prepayLabels');
            Route::get('admin/setup/account', 'Admin\SettingsController@account');
            Route::get('admin/setup/billing', 'Admin\SettingsController@billing');
            Route::get('admin/setup/invoices', 'Admin\SettingsController@invoices');
            Route::get('admin/setup/invoices/subscription-plan', 'Admin\SettingsController@subscriptionPlan');
            Route::get('admin/setup/invoices/prepaid-labels', 'Admin\SettingsController@stripeCharges');
            Route::get('admin/setup/instagram', 'Admin\SettingsController@instagram');
            Route::get('admin/setup/templates', 'Admin\SettingsController@templatesFacebook');
            Route::get('admin/setup/templates-emails', 'Admin\SettingsController@templatesEmails');
            Route::get('admin/setup/embed', 'Admin\SettingsController@embed');
            Route::get('admin/setup/labels', 'Admin\SettingsController@labels');
            Route::get('admin/setup/repost', 'Admin\SettingsController@repost');
            Route::get('admin/setup/shopify', 'Admin\SettingsController@shopify');
            Route::resource('admin/setup/locations', 'Admin\LocationSettingsController');
            Route::post('admin/setup/locations/enabled', 'Admin\LocationSettingsController@enableMultipleLocations')->name('enable_location');
            Route::post('admin/setup/locations/disabled', 'Admin\LocationSettingsController@disableMultipleLocations')->name('disable_location');
            Route::post('admin/setup/change-default-location', 'Admin\LocationSettingsController@changeDefaultLocation');
            Route::post('admin/setup/shop-name', 'Admin\SettingsController@shopName');
            Route::post('admin/setup/shop-description', 'Admin\SettingsController@shopDescription');
            Route::post('admin/setup/shop-address', 'Admin\SettingsController@shopAddress');
            Route::post('admin/setup/timezone', 'Admin\SettingsController@timezone');
            Route::post('admin/setup/expire', 'Admin\SettingsController@expire');
            Route::post('admin/setup/remind', 'Admin\SettingsController@remind');
            Route::post('admin/setup/shipping-cost', 'Admin\SettingsController@shippingCost');
            Route::post('admin/setup/variable-shipping-cost', 'Admin\SettingsController@variableShippingCost');
            Route::post('admin/setup/free-shipping-maximum', 'Admin\SettingsController@freeShippingMaximum');
            Route::post('admin/setup/password', 'Admin\SettingsController@updatePassword');
            Route::post('admin/setup/paypal-keys', 'Admin\SettingsController@paypalKeys');
            Route::post('admin/setup/goshippo-api-token', 'Admin\SettingsController@goshippoApiToken');
            Route::get('admin/setup/stripe-connect', 'Admin\SettingsController@stripeConnect');
            Route::post('admin/setup/local-pickup/enable', 'Admin\SettingsController@enableLocalPickup');
            Route::post('admin/setup/local-pickup/disable', 'Admin\SettingsController@disableLocalPickup');
            Route::post('admin/setup/24h-free-shipping/enable', 'Admin\SettingsController@enable24hrFreeShipping');
            Route::post('admin/setup/24h-free-shipping/disable', 'Admin\SettingsController@disable24hrFreeShipping');
            Route::post('admin/setup/update-card', 'Admin\SettingsController@updateCard');
            Route::post('admin/setup/templates/update', 'Admin\SettingsController@updateTemplate');
            Route::post('admin/setup/embed/update', 'Admin\SettingsController@updateEmbedCode');
            Route::post('admin/setup/labels/enable', 'Admin\SettingsController@enableLabels');
            Route::post('admin/setup/labels/disable', 'Admin\SettingsController@disableLabels');
            Route::post('admin/setup/repost/enable', 'Admin\SettingsController@enableRepost');
            Route::post('admin/setup/repost/disable', 'Admin\SettingsController@disableRepost');
            Route::post('admin/setup/repost/min-quantity', 'Admin\SettingsController@repostMinQuantity');
            Route::post('admin/setup/repost/days-since-last-post', 'Admin\SettingsController@repostDaysSinceLastPost');
            Route::post('admin/setup/repost/add-time', 'Admin\SettingsController@repostAddTime');
            Route::post('admin/setup/repost/remove-time', 'Admin\SettingsController@repostRemoveTime');
            Route::post('admin/setup/repost/enable-group', 'Admin\SettingsController@repostEnableGroup');
            Route::post('admin/setup/repost/disable-group', 'Admin\SettingsController@repostDisableGroup');
            Route::post('admin/setup/toggle-switch', 'Admin\SettingsController@toggleSwitch');
            Route::post('admin/setup/buy-prepaid-credit', 'Admin\SettingsController@buyPrepaidCredit');

            Route::post('admin/setup/connect-shopify', 'Admin\ShopifyController@connectShopify');
            Route::get('admin/setup/shopify-connect/callback', 'Admin\ShopifyController@shopifyCallback');
            Route::get('admin/setup/shopify-connected', 'Admin\ShopifyController@shopifyConnected');
            Route::post('admin/setup/shopify-unsync', 'Admin\ShopifyController@disconnectShopify');

            Route::get('admin/setup/instagram-connect', 'Admin\InstagramController@connect');
            Route::get('admin/setup/instagram-callback', 'Admin\InstagramController@adminCallback');

            Route::get('admin/setup/paypal-identity', 'Admin\PayPalController@identity');
            Route::get('admin/setup/paypal-identity-callback', 'Admin\PayPalController@identityCallback');

            Route::get('admin/facebook-setup', 'Admin\FacebookController@index');
            Route::get('admin/facebook-setup/messenger', 'Admin\FacebookController@messenger');
            Route::post('admin/facebook-setup/enable-group', 'Admin\FacebookController@enableGroup');
            Route::post('admin/facebook-setup/disable-group', 'Admin\FacebookController@disableGroup');
            Route::post('admin/facebook-setup/set-share-group', 'Admin\FacebookController@setShareGroup');
            Route::post('admin/api/facebook-setup/connect', 'Admin\FacebookController@connectFacebook');

app/Models/Coupon.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Coupon extends Model
{
    /**
     * The connection name for the model.
     *
     * @var string
     */
    protected $connection = 'shop';

    /**
     * Indicates if the model should be timestamped.
     *
     * @var bool
     */
    public $timestamps = true;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'code',
        'max_usage',
        'starts_at',
        'expires_at',
        'coupon_type',
        'amount',
        'shopify_coupon_id',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'options' => 'json',
    ];

    public function scopeSearch($query, $search = null)
    {
        if (! empty($search)) {
            $query->where('code', 'like', "%{$search}%");
        }

        return $query;
    }

    public function isTypeShipping()
    {
        return $this->coupon_type == 'S';
    }

    public function isTypeFixed()
    {
        return $this->coupon_type == 'F';
    }

    public function isTypePercentage()
    {
        return $this->coupon_type == 'P';
    }

    public function getShopifyType()
    {
        if ($this->isTypeShipping()) {
            return 'shipping';
        } elseif ($this->isTypeFixed()) {
            return 'fixed_amount';
        } elseif ($this->isTypePercentage()) {
            return 'percentage';
        }

        return null;
    }

    public static function getCoupon($code)
    {
        $code = strtoupper(trim($code));

        return static::where('code', $code)->first();
    }

    public function isActive()
    {
        if ($this->starts_at != 0 && $this->starts_at > time()) {
            return false;
        }

        if ($this->expires_at != 0 && $this->expires_at < time()) {
            return false;
        }

        if ($this->max_usage != 0 && $this->use_count >= $this->max_usage) {
            return false;
        }

        return true;
    }

    public function isValid($user, $subtotal)
    {
        // if it's an only once per customer, make sure it wasn't used
        if (isset($this->options['onlyOnce']) && $this->options['onlyOnce'] == '1') {
            $exists = app('App\Models\Order')->where('customer_id', '=', $user->id)
                ->where('coupon', '=', $this->code)->first();
            if (! is_null($exists)) {
                return false;
            }
        }

        // check if this is a promotional coupon that is valid for a limited time since the user signs up
        if (isset($this->options['newUsersPeriod']) && is_numeric($this->options['newUsersPeriod'])) {

            $validUntil = $user->created_at->addDays($this->options['newUsersPeriod']);
            $now = Carbon::now();

            if ($now->greaterThan($validUntil)) {
                return false;
            }
        }

        // check if the coupon can be used only by one user
        if (isset($this->options['userId']) && is_numeric($this->options['userId'])) {
            if ($this->options['userId'] != $user->id) {
                return false;
            }
        }

        // check subtotal is greater than minimum purchase amount
        if (isset($this->options['minPurchaseAmount']) && is_numeric($this->options['minPurchaseAmount']) && $this->options['minPurchaseAmount'] > 1) {
            if ($this->options['minPurchaseAmount'] > $subtotal) {
                return false;
            }
        }

        return $this->isActive();
    }

    public function saveCoupon(array $options = [])
    {
        $this->code = strtoupper(trim($this->code));

        if ($this->isTypeShipping()) {
            $this->amount = 0;
        }

        $this->starts_at = empty($this->starts_at) ? 0 : strtotime($this->starts_at);
        $this->expires_at = empty($this->expires_at) ? 0 : strtotime($this->expires_at);
        $this->max_usage = empty($this->max_usage) ? 0 : $this->max_usage;

        parent::save();
    }

    public function increaseUseCount()
    {
        if (is_null($this->use_count)) {
            $this->use_count = 0;
        }

        $this->use_count++;
        $this->save();
    }

    public function order()
    {
        return $this->belongsTo('App\Models\Order', 'code', 'coupon');
    }
}

app/Http/Controllers/Admin/ShopifyController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Http\Requests\Admin\ConnectShopifyFromRequest;
use App\Shopify\ShopifyClient;
use App\Shopify\Shopify;
use App\Jobs\HandleShopifyWebhook;
use App\Jobs\SetupShopify;
use Exception;
use Redis;
use Log;

class ShopifyController extends Controller
{
    /**
     * Shopify Webhook
     *
     * @return \Illuminate\Http\Response
     */
    public function incoming(Request $request)
    {
        $topic  = $request->header('X-Shopify-Topic');
        $sha256 = $request->header('X-Shopify-Hmac-Sha256');
        $shop   = $request->header('X-Shopify-Shop-Domain');
        $data   = file_get_contents('php://input');

        // dispatch(new HandleShopifyWebhook($request->all(), $topic, $sha256, $shop, $data));
        try {

            (new HandleShopifyWebhook($request->all(), $topic, $sha256, $shop, $data))->handle();

        } catch (Exception $e) {
            Log::error($e->getMessage());
            Log::info($shop);
            Log::info($topic);
            Log::info($request->all());
        }
    }

    public function connectShopify(ConnectShopifyFromRequest $request)
    {
        $client = new ShopifyClient(request('shopify_shop_name'));

        $nonce = uniqid();
        shop_setting_set('shopify.nonce', $nonce);

        return redirect($client->getAuthorizeUrl($nonce));
    }

    public function shopifyCallback(Shopify $shopify)
    {
        $client = new ShopifyClient(request('shop'));

        if (request('state') != shop_setting('shopify.nonce') || ! ends_with(request('shop'), '.myshopify.com') ||
            ! $client->validateSignature(request()->input()))
        {
            flash('Could not connect shopify. Security check failed!', 'danger');
            return redirect('/admin/setup/shopify');
        }

        $token = $client->getAccessToken(request('code'));
        if (! is_null($token)) {
            shop_setting_set('shopify.access_token', $token);
            shop_setting_set('shopify.shopify-shop-name', request('shop'));
            shop_setting_set('shopify.connecting', true);
            shop_setting_set('shopify.enabled', true);

            dispatch(new SetupShopify(shop_id()));

            // update the Redis cache
            Redis::connection('cache')->set("shopify-shop:".request('shop'), shop_id());

            flash('Shopify connected!');
            return redirect('/admin/setup/shopify');
        }

        flash('Something went wrong. Could not connect shopify.', 'danger');
        return redirect('/admin/setup/shopify');
    }

    public function shopifyConnected()
    {
        if (shop_setting('shopify.connecting') == false) {
            return response()->json(['status' => 1]);
        }

        return response()->json(['status' => 0]);
    }

    public function disconnectShopify()
    {
        try {

            (new Shopify)->deleteWebhooks();
            shop_setting_set('shopify.access_token', null);
            shop_setting_set('shopify.enabled', false);

        } catch (Exception $e) {
            Log::error($e->getMessage());
        }

        flash('Shopify was disconnected.');
        return redirect('/admin/setup/shopify');
    }
}

resources/views/themes/shopify/snippets/collection-grid-item.blade.php
{% unless collection_image_size %}
  {%- assign collection_image_size = '340x340' -%}
{% endunless %}
{%- assign collection_image_scale = '2' -%}

{% if collection.image %}
  {% capture collection_image_url %}{{ collection | img_url: collection_image_size, scale: collection_image_scale, crop: 'top' }}{% endcapture %}
{% elsif collection.products.first and collection.products.first.images != empty %}
  {% capture collection_image_url %}{{ collection.products.first | img_url: collection_image_size, scale: collection_image_scale, crop: 'top' }}{% endcapture %}
{% else %}
  {% assign collection_image_url = blank %}
{% endif %}
<div class="collection-grid-item">
  <a href="{% if collection.products == empty %}#{% else %}{{ collection.url }}{% endif %}" class="collection-grid-item__link">
    <div class="collection-grid-item__overlay"{% unless collection_image_url == blank %} style="background-image: url({{ collection_image_url }})"{% endunless %}></div>
    <div class="collection-grid-item__title-wrapper">
      <h3 class="collection-grid-item__title">
        {% if collection.title == blank %}
          {{ 'homepage.onboarding.collection_title' | t }}
        {% else %}
          {{ collection.title }}
        {% endif %}
      </h3>
    </div>
  </a>
</div>

resources/views/themes/shopify/snippets/comment.blade.php
<!-- /snippets/comment.liquid -->
<div class="comment__content rte">
  {{ comment.content }}
</div>
<div class="comment__meta">
  <span class="comment__meta-item">{{ comment.author }}</span>
  <span class="comment__meta-item">{{ comment.created_at | time_tag: format: 'month_day_year' }}</span>
</div>

resources/views/themes/shopify/snippets/pagination.blade.php
<ul class="list--inline pagination">
  <li>
    {% unless paginate.previous.is_link %}
      <div class="btn btn--secondary btn--narrow btn--disabled">
        {% include 'icon-arrow-left' %}
        <span class="icon__fallback-text">{{ 'general.pagination.previous' | t }}</span>
      </div>
    {% else %}
      <a href="{{ paginate.previous.url }}" class="btn btn--secondary btn--narrow">
        {% include 'icon-arrow-left' %}
        <span class="icon__fallback-text">{{ 'general.pagination.previous' | t }}</span>
      </a>
    {% endunless %}
  </li>
  <li class="pagination__text">
    {{ 'general.pagination.current_page' | t: current: paginate.current_page, total: paginate.pages }}
  </li>
  <li>
    {% unless paginate.next.is_link %}
      <div class="btn btn--secondary btn--narrow btn--disabled">
        {% include 'icon-arrow-right' %}
        <span class="icon__fallback-text">{{ 'general.pagination.next' | t }}</span>
      </div>
    {% else %}
      <a href="{{ paginate.next.url }}" class="btn btn--secondary btn--narrow">
        {% include 'icon-arrow-right' %}
        <span class="icon__fallback-text">{{ 'general.pagination.next' | t }}</span>
      </a>
    {% endunless %}
  </li>
</ul>

resources/views/themes/shopify/snippets/product-card-grid.blade.php
{% unless grid_image_width %}
  {%- assign grid_image_width = '300x300' -%}
{% endunless %}
{%- assign grid_image_scale = '2' -%}

<div class="grid-view-item{% unless product.available %} product-price--sold-out grid-view-item--sold-out{% endunless %}">
  <a class="grid-view-item__link" href="{{ product.url | within: collection }}">
    <img class="grid-view-item__image" src="{{ product.featured_image.src | img_url: grid_image_width, scale: grid_image_scale }}" alt="{{ product.featured_image.alt }}">
    <div class="h4 grid-view-item__title">{{ product.title }}</div>
    {% if section.settings.show_vendor %}
      <div class="grid-view-item__vendor">{{ product.vendor }}</div>
    {% endif %}
    <div class="grid-view-item__meta">
      {% include 'product-price' %}
    </div>
  </a>
</div>

resources/views/themes/shopify/snippets/product-card-list.blade.php
<div class="list-view-item__image-column">
  <div class="list-view-item__image-wrapper">
    <img class="list-view-item__image" src="{{ product.featured_image.src | img_url: '95x95', scale: 2 }}" alt="{{ product.featured_image.alt | escape }}">
  </div>
</div>

<div class="list-view-item__title-column">
  <div class="list-view-item__title">{{ product.title }}</div>
  {% if product.compare_at_price > product.price %}
    <div class="list-view-item__on-sale">{{ 'products.product.on_sale' | t }}</div>
  {% endif %}
  {% if section.settings.show_vendor %}
    <div class="list-view-item__vendor medium-up--hide">{{ product.vendor }}</div>
  {% endif %}
  {% unless product.available %}
    <div class="list-view-item__sold-out">{{ 'products.product.sold_out' | t }}</div>
  {% endunless %}
</div>

{% if section.settings.show_vendor %}
  <div class="list-view-item__vendor-column small--hide">
    <div class="list-view-item__vendor">{{ product.vendor }}</div>
  </div>
{% endif %}

<div class="list-view-item__price-column">
  {% include 'product-price' %}
</div>

resources/views/themes/shopify/snippets/product-price.blade.php
  <!-- snippet/product-price.liquid -->
  {% if product.title %}
    {%- assign compare_at_price = product.compare_at_price -%}
    {%- assign price = product.price -%}
    {%- assign price_varies = product.price_varies -%}
    {%- assign available = product.available -%}
  {% else %}
    {%- assign compare_at_price = 1999 -%}
    {%- assign price = 1999 -%}
    {%- assign price_varies = false -%}
    {%- assign available = true -%}
  {% endif %}

  {%- assign money_price = price | money -%}

  {% if compare_at_price > price %}
    {% if price_varies %}
      <span class="visually-hidden">{{ 'products.product.regular_price' | t }}</span>
      <s class="product-price__price">{{ compare_at_price | money }}</s>
      <span class="product-price__price product-price__sale">
        {{ money_price }}
        <span class="product-price__sale-label">{{ 'products.product.on_sale' | t }}</span>
      </span>
    {% else %}
      <span class="visually-hidden">{{ 'products.product.regular_price' | t }}</span>
      <s class="product-price__price">{{ compare_at_price | money }}</s>
      <span class="product-price__price product-price__sale">
        {{ money_price }}
        <span class="product-price__sale-label">{{ 'products.product.on_sale' | t }}</span>
      </span>
    {% endif %}
  {% else %}

    {% if price_varies %}
      <span class="product-price__price">{{ money_price }}</span>
    {% else %}
      <span class="visually-hidden">{{ 'products.product.regular_price' | t }}</span>
      <span class="product-price__price">{{ money_price }}</span>
    {% endif %}
  {% endif %}

  {% unless available %}
    <span class="product-price__sold-out">{{ 'products.product.sold_out' | t }}</span>
  {% endunless %}

resources/views/themes/shopify/snippets/search-form.blade.php
  <form action="/search" method="get" class="search-header search" role="search">
    <input class="search-header__input search__input"
      type="search"
      name="q"
      placeholder="{{ 'general.search.placeholder' | t }}"
      aria-label="{{ 'general.search.placeholder' | t }}">
    <button class="search-header__submit search__submit btn--link" type="submit">
      {% include 'icon-search' %}
      <span class="icon__fallback-text">{{ 'general.search.submit' | t }}</span>
    </button>
  </form>

resources/views/themes/shopify/snippets/site-nav.blade.php
  <ul class="site-nav list--inline {{ nav_alignment }}" id="SiteNav">
    {% for link in linklists[section.settings.main_linklist].links %}
      {%- assign child_list_handle = link.title | handleize -%}

      {% if linklists[child_list_handle].links != blank %}
        <li class="site-nav--has-dropdown{% if link.active %} site-nav--active{% endif %}">
          <a href="{{ link.url }}" class="site-nav__link site-nav__link--main" aria-has-popup="true" aria-expanded="false" aria-controls="SiteNavLabel-{{ child_list_handle }}">
            {{ link.title }}
            {% include 'icon-chevron-down' %}
            <span class="visually-hidden">{{ 'layout.navigation.expand' | t }}</span>
          </a>

          <div class="site-nav__dropdown" id="SiteNavLabel-{{ child_list_handle }}">
            <ul>
              {% for childlink in linklists[child_list_handle].links %}
                <li {% if childlink.active %}class="site-nav--active"{% endif %}>
                  <a href="{{ childlink.url }}" class="site-nav__link site-nav__child-link{% if forloop.last %} site-nav__link--last{% endif %}">{{ childlink.title | escape }}</a>
                </li>
              {% endfor %}
            </ul>
          </div>
        </li>
      {% else %}
        <li {% if link.active %}class="site-nav--active"{% endif %}>
          <a href="{{ link.url }}" class="site-nav__link site-nav__link--main">{{ link.title }}</a>
        </li>
      {% endif %}
    {% endfor %}
  </ul>

resources/views/themes/shopify/snippets/social-meta-tags.blade.php
  <!-- /snippets/social-meta-tags.liquid -->
  {%- assign og_title = page_title  -%}
  {%- assign og_url = canonical_url -%}
  {%- assign og_type = 'website' -%}
  {%- assign og_description = page_description | default: shop.description | default: shop.name -%}

  {% comment %} Template specific overides {% endcomment %}
  {%- if template.name == 'product' -%}
    {%- assign og_title = product.title | strip_html -%}
    {%- assign og_type = 'product' -%}
    {%- capture og_image_tags -%}{% for image in product.images limit:3 -%}<meta property="og:image" content="http:{{ image.src | product_img_url: '1024x1024' }}">{% endfor -%}{% endcapture -%}
    {%- capture og_image_secure_url_tags -%}{% for image in product.images limit:3 -%}<meta property="og:image:secure_url" content="https:{{ image.src | product_img_url: '1024x1024' }}">{% endfor -%}{% endcapture -%}

  {%- elsif template.name == 'article' -%}
    {%- assign og_title = article.title | strip_html -%}
    {%- assign og_type = 'article' -%}
    {%- assign og_description = article.excerpt_or_content | strip_html -%}
    {%- if article.image -%}
      {%- capture og_image_tags -%}<meta property="og:image" content="http:{{ article.image | img_url: '1024x1024' }}">{% endcapture -%}
      {%- capture og_image_secure_url_tags -%}<meta property="og:image:secure_url" content="https:{{ article.image | img_url: '1024x1024' }}">{% endcapture -%}
    {%- endif -%}

  {%- elsif template.name == 'password' -%}
    {%- assign og_title = shop.name -%}
    {%- assign og_url = shop.url -%}
    {%- assign og_description = shop.description | default: shop.name -%}
  {%- endif -%}

  <meta property="og:site_name" content="{{ shop.name }}">
  <meta property="og:url" content="{{ og_url }}">
  <meta property="og:title" content="{{ og_title }}">
  <meta property="og:type" content="{{ og_type }}">
  <meta property="og:description" content="{{ og_description }}">
  {%- if template.name == 'product' -%}
    <meta property="og:price:amount" content="{{ product.price | money_without_currency | strip_html }}">
    <meta property="og:price:currency" content="{{ shop.currency }}">
  {%- endif -%}
  {{ og_image_tags }}
  {{ og_image_secure_url_tags }}

  <meta name="twitter:site" content="{{ settings.social_twitter_link | split: 'twitter.com/' | last | prepend: '@' }}">
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:title" content="{{ og_title }}">
  <meta name="twitter:description" content="{{ og_description }}">