routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Admin routes that can be accessed only from the non-www main domain.
|
*/

Route::group(['domain' => env('APP_DOMAIN')], function() {

    // Facebook Messenger Webhooks
    Route::get('/messenger', 'Messenger\MessengerController@incoming');
    Route::post('/messenger', 'Messenger\MessengerController@incoming');
    Route::get('/messenger-test', 'Messenger\MessengerTestController@incoming');
    Route::post('/messenger-test', 'Messenger\MessengerTestController@incoming');

    // Facebook Webhooks
    Route::get('/facebook', 'Admin\FacebookController@incoming');
    Route::post('/facebook', 'Admin\FacebookController@incoming');

    // Instagram Webhooks
    Route::get('/instagram', 'Admin\InstagramController@incoming');
    Route::post('/instagram', 'Admin\InstagramController@incoming');

    // Shopify Webhooks
    Route::get('/shopify', 'Admin\ShopifyController@incoming');
    Route::post('/shopify', 'Admin\ShopifyController@incoming');

    // Authentication Routes...
    Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
    Route::post('login', 'Auth\LoginController@login');
    Route::post('logout', 'Auth\LoginController@logout')->name('logout');

    // Registration Routes...
    Route::get('register-invite', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::get('register-boutiquehub', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::get('register', 'Auth\RegisterController@showRegistrationForm')->name('register');
    Route::post('register', 'Auth\RegisterController@register');

    // Password Reset Routes...
    Route::get('password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.request');
    Route::post('password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
    Route::get('password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset');
    Route::post('password/reset', 'Auth\ResetPasswordController@reset');

    Route::get('/', 'Admin\WelcomeController@index');
    Route::get('contact', 'Admin\WelcomeController@contact');
    Route::get('pricing', 'Admin\WelcomeController@pricing');

    Route::get('facebook-login/callback', 'Shop\SocialAuthController@redirectToShop');
    Route::get('instagram-connect/callback', 'Admin\InstagramController@callback');

    Route::group(['middleware' => ['auth', 'shop.not-created']], function() {
        Route::get('admin/setup/step-1', 'Admin\CreateShopController@index');
        Route::post('admin/setup/step-1', 'Admin\CreateShopController@newShop');
        Route::post('admin/setup/hear-about-us', 'Admin\CreateShopController@setHearAboutUs');
        Route::post('admin/setup/billing-plan', 'Admin\CreateShopController@setBillingPlan');
    });

    Route::group(['middleware' => ['auth', 'shop.created', 'shop.has-no-card']], function() {
        Route::get('admin/setup/step-2', 'Admin\CreateShopController@card');
        Route::post('admin/setup/step-2', 'Admin\CreateShopController@setCard');
    });

    Route::group(['middleware' => ['auth', 'shop.created', 'shop.has-card']], function() {

        Route::get('admin', 'Admin\DashboardController@index');

        Route::group(['middleware' => ['can:superadmin']], function() {
            Route::get('admin/setup', 'Admin\SettingsController@shop');
            Route::get('admin/setup/shipping', 'Admin\SettingsController@shipping');
            Route::get('admin/setup/shipping/prepay-labels', 'Admin\SettingsController@prepayLabels');
            Route::get('admin/setup/account', 'Admin\SettingsController@account');
            Route::get('admin/setup/billing', 'Admin\SettingsController@billing');
            Route::get('admin/setup/invoices', 'Admin\SettingsController@invoices');
            Route::get('admin/setup/invoices/subscription-plan', 'Admin\SettingsController@subscriptionPlan');
            Route::get('admin/setup/invoices/prepaid-labels', 'Admin\SettingsController@stripeCharges');
            Route::get('admin/setup/instagram', 'Admin\SettingsController@instagram');
            Route::get('admin/setup/templates', 'Admin\SettingsController@templatesFacebook');
            Route::get('admin/setup/templates-emails', 'Admin\SettingsController@templatesEmails');
            Route::get('admin/setup/embed', 'Admin\SettingsController@embed');
            Route::get('admin/setup/labels', 'Admin\SettingsController@labels');
            Route::get('admin/setup/repost', 'Admin\SettingsController@repost');
            Route::get('admin/setup/shopify', 'Admin\SettingsController@shopify');
            Route::resource('admin/setup/locations', 'Admin\LocationSettingsController');
            Route::post('admin/setup/locations/enabled', 'Admin\LocationSettingsController@enableMultipleLocations')->name('enable_location');
            Route::post('admin/setup/locations/disabled', 'Admin\LocationSettingsController@disableMultipleLocations')->name('disable_location');
            Route::post('admin/setup/change-default-location', 'Admin\LocationSettingsController@changeDefaultLocation');
            Route::post('admin/setup/shop-name', 'Admin\SettingsController@shopName');
            Route::post('admin/setup/shop-description', 'Admin\SettingsController@shopDescription');
            Route::post('admin/setup/shop-address', 'Admin\SettingsController@shopAddress');
            Route::post('admin/setup/timezone', 'Admin\SettingsController@timezone');
            Route::post('admin/setup/expire', 'Admin\SettingsController@expire');
            Route::post('admin/setup/remind', 'Admin\SettingsController@remind');
            Route::post('admin/setup/shipping-cost', 'Admin\SettingsController@shippingCost');
            Route::post('admin/setup/variable-shipping-cost', 'Admin\SettingsController@variableShippingCost');
            Route::post('admin/setup/free-shipping-maximum', 'Admin\SettingsController@freeShippingMaximum');
            Route::post('admin/setup/password', 'Admin\SettingsController@updatePassword');
            Route::post('admin/setup/paypal-keys', 'Admin\SettingsController@paypalKeys');
            Route::post('admin/setup/goshippo-api-token', 'Admin\SettingsController@goshippoApiToken');
            Route::get('admin/setup/stripe-connect', 'Admin\SettingsController@stripeConnect');
            Route::post('admin/setup/local-pickup/enable', 'Admin\SettingsController@enableLocalPickup');
            Route::post('admin/setup/local-pickup/disable', 'Admin\SettingsController@disableLocalPickup');
            Route::post('admin/setup/24h-free-shipping/enable', 'Admin\SettingsController@enable24hrFreeShipping');
            Route::post('admin/setup/24h-free-shipping/disable', 'Admin\SettingsController@disable24hrFreeShipping');
            Route::post('admin/setup/update-card', 'Admin\SettingsController@updateCard');
            Route::post('admin/setup/templates/update', 'Admin\SettingsController@updateTemplate');
            Route::post('admin/setup/embed/update', 'Admin\SettingsController@updateEmbedCode');
            Route::post('admin/setup/labels/enable', 'Admin\SettingsController@enableLabels');
            Route::post('admin/setup/labels/disable', 'Admin\SettingsController@disableLabels');
            Route::post('admin/setup/repost/enable', 'Admin\SettingsController@enableRepost');
            Route::post('admin/setup/repost/disable', 'Admin\SettingsController@disableRepost');
            Route::post('admin/setup/repost/min-quantity', 'Admin\SettingsController@repostMinQuantity');
            Route::post('admin/setup/repost/days-since-last-post', 'Admin\SettingsController@repostDaysSinceLastPost');
            Route::post('admin/setup/repost/add-time', 'Admin\SettingsController@repostAddTime');
            Route::post('admin/setup/repost/remove-time', 'Admin\SettingsController@repostRemoveTime');
            Route::post('admin/setup/repost/enable-group', 'Admin\SettingsController@repostEnableGroup');
            Route::post('admin/setup/repost/disable-group', 'Admin\SettingsController@repostDisableGroup');
            Route::post('admin/setup/toggle-switch', 'Admin\SettingsController@toggleSwitch');
            Route::post('admin/setup/buy-prepaid-credit', 'Admin\SettingsController@buyPrepaidCredit');

            Route::post('admin/setup/connect-shopify', 'Admin\ShopifyController@connectShopify');
            Route::get('admin/setup/shopify-connect/callback', 'Admin\ShopifyController@shopifyCallback');
            Route::get('admin/setup/shopify-connected', 'Admin\ShopifyController@shopifyConnected');
            Route::post('admin/setup/shopify-unsync', 'Admin\ShopifyController@disconnectShopify');

            Route::get('admin/setup/instagram-connect', 'Admin\InstagramController@connect');
            Route::get('admin/setup/instagram-callback', 'Admin\InstagramController@adminCallback');

            Route::get('admin/setup/paypal-identity', 'Admin\PayPalController@identity');
            Route::get('admin/setup/paypal-identity-callback', 'Admin\PayPalController@identityCallback');

            Route::get('admin/facebook-setup', 'Admin\FacebookController@index');
            Route::get('admin/facebook-setup/messenger', 'Admin\FacebookController@messenger');
            Route::post('admin/facebook-setup/enable-group', 'Admin\FacebookController@enableGroup');
            Route::post('admin/facebook-setup/disable-group', 'Admin\FacebookController@disableGroup');
            Route::post('admin/facebook-setup/set-share-group', 'Admin\FacebookController@setShareGroup');
            Route::post('admin/api/facebook-setup/connect', 'Admin\FacebookController@connectFacebook');

resources/views/admin/setup/embed.blade.php
@extends('admin.setup.setup')

@section('section', 'Embed')

@section('setup')
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body">
                <form class="form" id="embed-code-form" role="form" method="POST" action="{{ url('/admin/setup/embed/update') }}">
                    <span class="settings-info">Embed Code</span>
                    <span class="settings-muted text-muted">
                        You can embed any custom code on your shop page. For example, you can add your Google Analytics, Facebook Pixel or Zendesk. This will be added at the bottom of the page.
                    </span>

                    <div class="form-group @hasError('embed_code')">
                        <label class="control-label">Code</label>
                        <textarea class="form-control" rows="10" id="embed-code" name="embed_code">{{ old('embed_code', shop_setting('embed-code')) }}</textarea>
                        @error('embed_code')
                        <span class="help-block"><strong></strong></span>
                    </div>

                    <button class="btn btn-success" type="submit">Update Code</button>
                </form>

            </div>
        </div>
    </div>
</div>
<div style="display: none;" id="validate-code"></div>
@endsection

@section('scripts')
<script type="text/javascript">
    $(document).ready(function() {
        $('#embed-code-form').submit(function() {
            try {
                var code = $('#embed-code').val();

                // validate for js errors; a js error will be thrown if invalid
                $('#validate-code').html(code);

                // validate that the nr of open tags is the same as the nr of closed tags
                checkTags(code, ['script', 'span', 'div', 'strong']);
                return true;

            } catch(e) {
                $('.form-group', $(this)).addClass('has-error');
                $('.help-block strong', $(this)).html('There is a error in your code. Please fix your code and try again.');
                return false;
            }
        });
    });

    function checkTags(code, tags) {
        for (var i = 0; i < tags.length; i++) {
            var nrOpen = (code.match(new RegExp('<' + tags[i] + '>', 'gi')) || []).length;
            var nrClosed = (code.match(new RegExp('<\/' + tags[i] + '>', 'gi')) || []).length;

            if (nrOpen != nrClosed) {
                throw new Error('Tags mismatch');
            }
        }
    }
</script>
@endsection

resources/views/admin/setup/facebook-groups.blade.php
@extends('admin.setup.facebook-setup')

@section('section', 'Facebook Groups')

@section('setup')
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body lr-m-15">

                <h3 style="margin-top: 0px;">Groups</h3>

                @if (empty($groups))
                    You don't have access to any groups with your facebook account. Visit <a href="https://facebook.com/">facebook</a> and create or join an existing facebook group as an admininstrator.
                @else
                    Below is a list of groups in your account. You need to be an administrator to post to these groups.<br/><br/>
                    To create a post, go to <a href="/admin/products">Products</a> and click on the "Post to Facebook" option to post that product.<br/><br/>

                    You can enable/disable multiple facebook groups where comments will be read from. You can also choose what facebook group to enable for the Facebook Share Button on the shop /account page. (only one group can be shared)<br/><br/>

                    @if (empty($enabledGroups))
                        You need to specify the group or groups that will be used for this shop.<br/><br/>
                    @endif

                    @foreach ($groups as $group)
                        <div class="row">
                            <div class="col-md-6">
                                <div class="table-responsive">
                                    <table class="table">
                                        <tr>
                                            <td style="width:33%;">
                                                <a class="" href="https://www.facebook.com/{{ $group['id'] }}" target="_blank">{{ $group['name'] }}</a>
                                                @if (in_array($group['id'], $enabledGroups))
                                                    &nbsp;<strong>(Enabled)</strong>
                                                @endif
                                            </td>
                                            <td style="width:33%;">
                                                @if (in_array($group['id'], $enabledGroups))
                                                    <form class="form-horizontal" role="form" method="POST" action="/admin/facebook-setup/disable-group">
                                                        <input type="hidden" name="group_id" value="{{ $group['id'] }}">
                                                        <button type="submit" data-loading-text="Disabling Group.." class="btn btn-danger">Disable Group</button>
                                                    </form>
                                                @else
                                                    <form class="form-horizontal" role="form" method="POST" action="/admin/facebook-setup/enable-group">
                                                        <input type="hidden" name="group_id" value="{{ $group['id'] }}">
                                                        <button type="submit" data-loading-text="Enabling Group.." class="btn btn-default">Enable Group</button>
                                                    </form>
                                                @endif
                                            </td>
                                            <!--
                                            <td style="width:33%;">
                                                @if ($group['id'] == shop_setting('facebook.share-group-id'))
                                                    <strong>(Facebook sharing button Enabled)</strong>
                                                @else
                                                    <form class="form-horizontal" role="form" method="POST" action="/admin/facebook-setup/set-share-group">
                                                        <input type="hidden" name="group_id" value="{{ $group['id'] }}">
                                                        <button type="submit" data-loading-text="Enabling Share Button.." class="btn btn-default">Enable Share Button for this Group</button>
                                                    </form>
                                                @endif
                                            </td>
                                            -->
                                        </tr>
                                    </table>
                                </div>
                            </div>
                        </div>
                    @endforeach
                @endif

            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/setup/facebook-messenger.blade.php
@extends('admin.setup.facebook-setup')

@section('section', 'Facebook Messenger')

@section('setup')
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body lr-m-15">

                <h3 style="margin-top: 0px;">Messenger</h3>

                The Facebook Messenger requires a Facebook Page.<br/><br/>
                @if (empty($pages))
                    You don't have access to any pages with your Facebook account. Visit <a href="https://www.facebook.com/">Facebook</a> and create a Facebook page.
                @else
                    Below is a list of pages in your account. Please choose what Page to use for the Facebook Messenger. Only one page can be used.
                    <br/><br/>

                    <div class="row">
                        <div class="col-md-6">
                            <div class="table-responsive">
                                <table class="table">
                                    <tr>
                                        <th>Page</th>
                                        <th>Category</th>
                                        <th>Manage</th>
                                    </tr>
                                    @foreach ($pages as $page)
                                        <tr>
                                            <td style="width:33%;">
                                                <a class="" href="https://www.facebook.com/{{ $page['id'] }}" target="_blank">{{ $page['name'] }}</a>
                                                @if ($page['id'] == $pageId)
                                                    &nbsp;<strong>(Enabled)</strong>
                                                @endif
                                            </td>
                                            <td style="width:33%;">{{ $page['category'] }}</td>
                                            <td style="width:33%;">
                                                @if ($page['id'] == $pageId)
                                                    <form class="form-horizontal" role="form" method="POST" action="/admin/facebook-setup/messenger/disable-page">
                                                        <input type="hidden" name="page_id" value="{{ $page['id'] }}">
                                                        <button type="submit" data-loading-text="Disabling Page.." class="btn btn-danger">Disable Page</button>
                                                    </form>
                                                @else
                                                    <form class="form-horizontal" role="form" method="POST" action="/admin/facebook-setup/messenger/enable-page">
                                                        <input type="hidden" name="page_id" value="{{ $page['id'] }}">
                                                        <button type="submit" data-loading-text="Enabling Page.." class="btn btn-default">Enable Page</button>
                                                    </form>
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                </table>
                            </div>
                        </div>
                    </div>
                @endif

            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body">
                <span class="settings-info">Automated Page Response</span>

                <div class="checkbox-inline"><label><input type="checkbox" data-key="messenger.send-contact-message" @if(shop_setting('messenger.send-contact-message', false)) checked="" @endif class="toggle-switch"></label></div>

                <span class="settings-muted text-muted">
                    If enabled, when a customer writes a message to your Facebook page, he will get this automated response:
                    "Hello, please contact {{ shop_email() }} for support. Thank you!".
                </span>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/setup/instagram.blade.php
@extends('admin.setup.setup')

@section('section', 'Instagram')

@section('setup')
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body">
                @if (shop_setting('instagram.token'))
                    <span class="label label-success">CONNECTED</span>
                    <span class="settings-info">Your Instagram account is connected!</span><br/><br/>

                    <h4>You are connected as <strong>{{ shop_setting('instagram.nickname') }}</strong></h4>
                    <img class="thumbnail" src="{{ shop_setting('instagram.avatar') }}">

                    <a class="btn btn-info btn-lg" href="/admin/setup/instagram-connect">Re-connect Instagram</a>
                @else
                    <span class="settings-info">Connect Your Instagram Account</span><br/>
                    <a class="btn btn-info btn-lg" href="/admin/setup/instagram-connect">Connect Instagram</a>
                @endif
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/setup/locations.blade.php
@extends('admin.setup.shipping.shipping')

@section('setup')
@include('admin.modals.delete-confirm')
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body">
                <span class="settings-info">Multiple Locations</span>
                <span class="settings-muted">If you have multiple local pickup locations, you can enable this option to allow the customer to choose which store location he wants to use. The tax applied will be the highest from all the locations entered.</span>
                <hr/>

                @if (local_pickup_enabled())
                    @if (multiple_locations_enabled())
                        <span class="settings-info">Multiple Locations: (Enabled)</span>
                        <form class="" role="form" method="POST" action="{{ route('disable_location') }}">
                            <button class="btn btn-danger test" type="submit">Disable Multiple Locations</button>
                        </form>
                    @else
                        <span class="settings-info">Multiple Locations: (Disabled)</span>
                        <form class="" role="form" method="POST" action="{{ route('enable_location') }}">
                            <button class="btn btn-success test" type="submit">Enable Multiple Locations</button>
                        </form>
                    @endif
                @else
                    <span class="settings-info">To enable multiple locations, first enable local pick-up.</span>
                @endif
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <div class="box">
            <div class="box-body">

                <div id="final_msg" style="display:none;" class="alert alert-success">
                    <strong>Success!</strong> Location updated.
                </div>
                <div class="col-xs-12 form-group row">
                    <div id="form-errors"></div>
                    @if ($errors->any())
                        <div class="alert alert-danger">
                            <ul>
                                @foreach ($errors->all() as $error)
                                    <li>{{ $error }}</li>
                                @endforeach
                            </ul>
                        </div>
                    @endif
                    <button type="button" class="btn btn-primary add_button">Add+</button>
                </div>
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th>Location</th>
                                <th>State</th>
                                <th>Zip Code</th>
                                <th>Address</th>
                                <th>Default</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                        @foreach($locations as $location)
                            <tr data-id="{{$location->id}}">
                                <td data-info="location">{{ $location->location }}</td>
                                <td data-info="state">{{ $location->state }}</td>
                                <td data-info="zip_code">{{ $location->zip_code }}</td>
                                <td data-info="address">{{ $location->address }}</td>
                                <td><input @if($location->isDefault()) checked @endif name="default" type="radio"></td>
                                <td>
                                    <a class="btn btn-primary edit_form" href="javascript:">Edit</a>
                                    <form method="Post" style="display:inline-block" action="{{ route('locations.destroy', $location->id ) }}">
                                        <input name="_method" type="hidden" value="DELETE">
                                        <input data-toggle="modal" data-target="#confirmDelete" class="btn btn-danger delete_tr" type="button" value="Delete">
                                    </form>
                                </td>
                             </tr>
                            <tr data-id="{{$location->id}}" style="display: none">
                                <td><input name="location" type="text" class="form-control" value="{{ $location->location }}"></td>
                                <td>
                                    <select class="form-control" name="state">
                                        @include('common.states', ['selected' => $location->state])
                                    </select>
                                </td>
                                <td><input name="zip_code" type="text" class="form-control" value="{{ $location->zip_code }}"></td>
                                <td><input name="address" type="text" class="form-control" value="{{ $location->address }}"></td>
                                <td></td>
                                <td><input class="btn btn-warning update_form" type="button" value="Update">
                                    <a href="javascript:" class="btn btn-default cancel">Cancel</a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="row">
                    <form method="post" action="{{ route('locations.store') }}" class="@if (!count($errors)>0) invisible @endif  form">
                        {{ csrf_field() }}
                        <div class="form-group col-md-3">
                            <label for="location">Location</label>
                            <input name="location" value="{{ old('location') }}" class="form-control" id="location" type="text">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="state">State</label>
                            <select class="form-control" name="state">
                                <?php $selected = old('state', shop_setting('shop.state')); ?>
                                @if (is_null($selected))
                                    <option value="" selected="selected">State..</option>
                                @endif
                                @include('common.states', compact('selected'))
                            </select>
                        </div>
                        <div class="form-group col-md-3">
                            <label for="zip-code">Zip Code</label>
                            <input name="zip_code" class="form-control" value="{{ old('zip_code') }}" id="zip-code" type="text">
                        </div>
                        <div class="form-group col-md-3">
                            <label for="address">Address</label>
                            <input name="address" class="form-control" value="{{ old('address') }}" id="address" type="text">
                        </div>
                        <div class="form-group col-xs-12">
                            <input class="btn btn-primary" type="submit" value="Save">
                            <a href="javascript:" id="cancel" name="cancel" class="btn btn-default">Cancel</a>
                        </div>
                    </form>
                </div>

            </div>
        </div>
    </div>
</div>
@endsection

@section('scripts')
    <script type="text/javascript" src="{{ asset('js/custom_admin.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function(){
            $('#confirmDelete').on('show.bs.modal', function (e) {
                $message = $(e.relatedTarget).attr('data-message');
                $(this).find('.modal-body p').text($message);
                $title = $(e.relatedTarget).attr('data-title');
                $(this).find('.modal-title').text($title);
                // Pass form reference to modal for submission on yes/ok
                var form = $(e.relatedTarget).closest('form');
                $(this).find('.modal-footer #confirm').data('form', form);
            });
            // Form confirm (yes/ok) handler, submits form
            $('#confirmDelete').find('.modal-footer #confirm').on('click', function () {
                console.log($(this).data('form'));
                $(this).data('form').submit();
            });
        });
    </script>
@endsection

resources/views/admin/setup/templates.blade.php
@extends('admin.setup.setup')

@section('section', 'Templates')

@section('sub-nav')
{{--
<div class="nav-subtabs-custom">
    <a class="{{ activeLink('admin/setup/templates') }}" href="/admin/setup/templates">Facebook Comments</a> |
    <a class="{{ activeLink('admin/setup/templates-emails') }}" href="/admin/setup/templates-emails">Emails</a>
</div>
--}}
@endsection